name: Testing new terraform code
on:
  push:
    branches:
      - develop
    paths:
      - '**.tf'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Install Go
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.6'

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: main

      - name: Testing
        - run go test -v