name: Testing new terraform code
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      -
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Setup Dependencies
      run:  go mod init test && go get -v -t -d ./test && go mod tidy && cat go.mod go.sum

    - name: Test
      run: go test -v ./test